### ISSUE TITLE
Documentation, Just syntax highlighting, or formatting, too?

### ISSUE THREAD

**Issue by cwhii** [elazarcoh/cpp2-syntax#2]
README.md  states 'This extension provides syntax highlighting'.

Is it limited to just highlighting or does it include formatting?

**Comment by elazarcoh** [comment]
Only syntax highlight.
I currently don't intend to actively add more features, except for fixing and updating the syntax highlight.
I may accept PR but it might be better to start off a new repo first and maybe merge it all into a single `cpp2` extension pack.
